#!/usr/bin/env bash

# animate (for skeletons)
animate() {
  local lastdir="$PWD"
  cd "$(dirname "$0")"
  local thisdir="$PWD"
  cd '..'
  local rootdir="$PWD"

  function do_xray() { "$thisdir/xray" $@; }
  function do_get_bone() {
    local bonefile="$thisdir/bones/$1"
    if test -f "$bonefile"; then
      cat "$bonefile"
    else
      echo 'missing_bones'
      return 1
    fi
  }
  function bone_mass() {
    ! test -f "$1" \
      && return 1
    local mass=$(du "$1" \
      | sed -E 's/(^[0-9]+).*/\1/g' 2>/dev/null)
    case $mass in
      ''|*[!0-9]*) echo 0;;
      *) echo $mass;;
    esac
  }
  function is_hollowbone() {
    ! test -f "$1" \
      && return 1
    local mass=$(bone_mass "$1")
    test $mass -gt 0
    return $?
  }

  for skeleton_file in $(do_xray --where --friskroot | tr '{' '\{'); do
    for skeleton_bone in $(do_xray --what --friskroot); do
      if ! is_hollowbone "$thisdir/bones/$skeleton_bone"; then
        echo "$*" | grep -q -- '--verbose' \
            && echo ":: $skeleton_bone => $skeleton_file"
        cat "$skeleton_file" | grep -q -- "$skeleton_bone" && {
          local snr="s/$skeleton_bone/$(do_get_bone "$skeleton_bone")/g"
          sed "$snr" "$skeleton_file" \
            > "$skeleton_file.skelnew" \
            || return 1
          echo "$*" | grep -q -- '--verbose' \
            && diff "$skeleton_file" "$skeleton_file.skelnew"
          echo "$*" | grep -q -- '--commit' \
            && mv "$skeleton_file.skelnew" "$skeleton_file"
        }
      else
        echo "$*" | grep -q -- '--verbose' \
          && echo ":: $skeleton_bone => <hollow>"
      fi
    done
  done

  cd "$lastdir"
}

animate "$@"
exit $?