#! /usr/bin/env bash

which awk &> /dev/null \
  && export PATH="$(\
    printf "%s" "$PATH" \
      | awk -v RS=':' '!a[$1]++ \
      { \
        if (NR > 1) \
        printf RS; \
        printf $1 \
      }')"
