#!/bin/sh

# From-Repo: pistacheio/pistache
# From-File: github.com/pistacheio/pistache/blob/master/.hooks/pre-commit
# SPDX-FileCopyrightText: 2021 Andrea Pappacoda
# SPDX-License-Identifier: Apache-2.0

for file in `git diff-index --cached --name-only HEAD | grep -E '\.(cpp|cc|hpp|h)$'` ; do
    clang-format --dry-run --Werror "$file" >/dev/null 2>&1 || {
      echo 'run clang-format before committing' 1>&2;
      false;
    }
done
